const fs = require('fs')
const c = fs.readFileSync('C:/Users/4513/.openclaw/workspace/jiugong-bagua/src/app/huangli/HuangliClient.tsx','utf8').replace(/\r\n/g,'\n')
const idx = c.indexOf('二十四节气表')
console.log('idx:', idx)
const beforeSec = c.lastIndexOf('      <div className="bg-white', idx)
console.log('beforeSec:', beforeSec)
const afterSec = c.indexOf('      {/* ', idx + 10)
console.log('afterSec:', afterSec)
console.log('Rest:', c.substring(afterSec, afterSec+200))
